In [98]:
#import libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')

In [99]:
#load data
digits=load_digits()

In [100]:
#split the training and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [101]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [102]:
lr.score(X_test,y_test)

0.9481481481481482

In [103]:
svm=SVC()
svm.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [104]:
svm.score(X_test,y_test)

0.2833333333333333

In [105]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [106]:
rf.score(X_test,y_test)

0.9611111111111111

In [107]:
#By using KFold validation technique
from sklearn.model_selection import KFold
#Here n_splits is no.of folds
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [108]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index], \
                                digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))
    

In [109]:
print("Logisticregression scores:",scores_l)
print("Svm score:",scores_svm)
print("Randomforestclassifier score:",scores_rf)

Logisticregression scores: [0.8964941569282137, 0.9515859766277128, 0.9115191986644408]
Svm score: [0.41068447412353926, 0.41569282136894825, 0.4273789649415693]
Randomforestclassifier score: [0.9198664440734557, 0.9382303839732888, 0.9181969949916527]


In [110]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [111]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold()

In [112]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_idex,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index], \
                                digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))
    

In [113]:
scores_l

[0.998330550918197, 0.998330550918197, 0.9115191986644408]

In [114]:
scores_svm

[1.0, 1.0, 0.4273789649415693]

In [115]:
scores_rf

[1.0, 1.0, 0.9165275459098498]

In [118]:
#By using cross_validation
from sklearn.model_selection import cross_val_score

In [119]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.89534884, 0.94991653, 0.90939597])

In [120]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.39368771, 0.41068447, 0.45973154])

In [121]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.90033223, 0.90651085, 0.90604027])